### ISSUE TITLE
Nakijken

### ISSUE THREAD

**Issue by HawkeyNL** [hanaim-devops/devops-blog-gus-theunissen#1]

**Comment by bartvanderwal** [comment]
Hoi Gus,
Dit ziet er goed uit! 

Edit: Of in ieder geval veelbelovend.

Ik had graag nog een overzichtsplaatje gezien, met schema van gebruik Sentry in ee.

Maar je hebt wel plaatjes, en alle andere eisen voldoe je ook aan. Alleen bij de bronen heb je alleen maar landfingspagina's. Geen echte blogs/tutorials of achtergrondartikelen met ook een auteur. En een datum. Kun je daar nog iets van vinden? Je hebt wel een onderzoeksplan. Daarin nog een iets meer deep link naar 'issues' page van Sentry.

Je zit al op 2700 woorden. Maar kun je niet kort wat alternatieven noemen voor Sentry, met nog een korte deelvraag, en daarbij tenminste een fatsoenlijke overzichtsbron geven? Want het is nu allemaal wel erg gericht op handson.

**Comment by bartvanderwal** [comment]
Alleen later ga je nat op APA. Zie beoordelingsformulier de ik heb ingevuld.

Graag re-openen als je heb geherkanst.
